#!/bin/bash

# Programmer: Chris Blanks
# Purpose: This script is supposed to pull the quote of the day from
# wwww.brainyquote.com and display the image.
# Dependency: ImageMagick's 'display' function (it's pretty handy)
#

export DISPLAY=:0.0  #allows access to Xserver

#change the following to where you saved this script
cd '/home/chrisblanks/projects/bash/utility_scripts/quote_of_the_day'

wget https://www.brainyquote.com/quote_of_the_day  #retrieves html from page
grep 'data-img-url' quote_of_the_day | cat > link.txt #find quote of the day image anchor & write to file

link=$(cat link.txt) #read link into variable
list=( $link )       #create space delimited list from link string

for i in ${list[*]}   #iterate through every element in list
do
  if [[ $i == *'data-img-url'* ]]  #checks to see if 'data-img-url' is a substring to list elements
  then
    echo 'found it:' $i
    input=$i
    input_list=(${input//=/ }) #replaces '=' with space & splits str into a list with parentheses
  fi
done

img_path=${input_list[1]} #second argument of input list should be link to data

img_path="${img_path%\"}" #removes suffix quote around link
img_path="${img_path#\"}" #removes prefix quote around link

temp=(${img_path//\// }) #splits url of data image by '/'s into a list
quote_of_the_day_img=${temp[-1]}  
#grabs the last index of the split url because it's the picture name w/ file extension

if [ -e $quote_of_the_day_img ]  #if img already exists in file system then don't grab another
then 
  echo "Already retrieved quote of the day!"
else 
  echo "Need to get file!"
  echo ""
  wget "https://www.brainyquote.com$img_path" #builds url path to image
fi

/usr/bin/display -delay 10  $quote_of_the_day_img  &>log.txt

rm link.txt quote_of_the_day* #removes unnecessary files
